module_separator = " "
reset_color = false

[bookmarks]
search_depth = 100
exclude = []

[[module]]
type = "Bookmarks"
separator = " "
color = "Magenta"
behind_symbol = "â‡¡"
surround_with_quotes = false

[[module]]
type = "Commit"
max_length = 24
empty_text = "(no desc)"
surround_with_quotes = true

[[module]]
type = "State"
separator = " "

[module.conflict]
disabled = false
text = "(conflict)"
color = "Red"

[module.divergent]
disabled = false
text = "(divergent)"
color = "Cyan"

[module.empty]
disabled = false
text = "(empty)"
color = "Yellow"

[module.immutable]
disabled = false
text = "(immutable)"
color = "Yellow"

[module.hidden]
disabled = false
text = "(hidden)"
color = "Yellow"

[[module]]
type = "Metrics"
template = "[{changed} {added}{removed}]"
color = "White"

[module.changed_files]
prefix = ""
suffix = ""
color = "Cyan"

[module.added_lines]
prefix = "+"
suffix = ""
color = "Green"

[module.removed_lines]
prefix = "-"
suffix = ""
color = "Red"
