"$schema" = 'https://starship.rs/config-schema.json'

format = """
$username\
$hostname\
$shlvl\
$directory\
${custom.git}\
${custom.jj}\
$docker_context\
${env_var.flox_env}\
$direnv\
$python\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$battery\
$os\
$container\
$character
"""

palette = "catppuccin_macchiato"

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[cmd_duration]
min_time = 120_000
format = " took [$duration]($style)"

[directory]
style = "bold lavender"
truncation_length = 8

[env_var.flox_env]
variable = "FLOX_ENV_DESCRIPTION"
format = " [flox](bold fg:99) [$env_value](bold fg:141) "

[direnv]
disabled = false
format = " [$symbol$loaded/$allowed]($style) "

[python]
format = "[$virtualenv](bold yellow) "

[git_branch]
format = "[$branch(:$remote_branch)](bold overlay1) "

[custom.git]
format = "$output"
ignore_timeout = true
shell = ["sh", "--norc", "--noprofile"]
command = "starship module git_branch; starship module git_state; starship module git_status"
when = "! jj root --ignore-working-copy"

[custom.jj]
format = "$output"
ignore_timeout = true
shell = ["sh", "--norc", "--noprofile"]
command = "starship-jj --ignore-working-copy starship prompt"
when = "jj root --ignore-working-copy"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
mauve = "#c6a0f6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
