"$schema" = "https://yazi-rs.github.io/schemas/keymap.json"

[mgr]

prepend_keymap = [
  { on = "f", run = "plugin jump-to-char", desc = "Jump to char" },
  { on = "l", run = "plugin smart-enter", desc = "Enter the child directory, or open the file" },

  { on = ["c", "m"], run = "plugin chmod", desc = "chmod on selected files" },

  { on = "<C-1>", run = "plugin toggle-pane max-parent", desc = "Maximize or restore the parent pane" },
  { on = "<C-2>", run = "plugin toggle-pane max-current", desc = "Maximize or restore the current pane" },
  { on = "<C-3>", run = "plugin toggle-pane max-preview", desc = "Maximize or restore the preview pane" },
]

append_keymap = [
  { on = ["g", "."], run = "cd ~/.dotfiles", desc = "Go ~/.dotfiles" },
  { on = ["g", "r"], run = 'shell -- ya emit cd "$(git root)"', desc = "cd back to the root of the current Git repository" },
]
