name: Update Flake Inputs
on:
  schedule:
    - cron: '0 4 * * *' # every day at 04:00 UTC
  workflow_dispatch: # allows manual triggering
jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v6
      - uses: cachix/install-nix-action@v31
      - name: Update flake inputs
        run: |-
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          nix flake update \
            --option access-tokens "github.com=${{ secrets.GITHUB_TOKEN }}" \
            --refresh \
            --commit-lock-file \
            --commit-lockfile-summary "flake: update all inputs" \
            --flake .
          git push
