name: "Update Flake Inputs"
on:
  workflow_dispatch: # allows manual triggering
  schedule:
    - cron: '0 4 * * *' # run daily at 04:00 UTC
jobs:
  nix-flake-update:
    permissions:
      contents: write
      # id-token: write
      # issues: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-substituters = https://cache.garnix.io https://cache.nixos.org/
            extra-trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= cache.garnix.io:CTFPyKSLcx5RMJKfLo5EEPUObbA78b0YQ2DTCJXqr9g=
      - uses: DeterminateSystems/update-flake-lock@main
        with:
          pr-title: "flake: update all inputs"
          pr-labels: |- # Labels to be set on the PR
            dependencies
            automated
